version: "1.0"

services:
    app:
        image: maven:3.6.1-jdk-8
        # 这里-Dspring.profiles.active=docker一定要在jar文件之前，否则无法识别
        command: sh -c "java -jar -Dspring.profiles.active=docker target/community-0.0.1-SNAPSHOT.jar"
        ports:
            - 8080:8080
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: todos
        depends_on: 
            - kafka
            - mysql
            - redis

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka:2.13-2.6.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            # KAFKA_ADVERTISED_HOST_NAME: "127.0.0.1"
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
        depends_on: 
            - zookeeper

    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-dump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: community

    redis:
        image: redis
        ports:
            - "6379:6379"